name: accloudtant
dependencies:
- openssl=1.0.1k=1
- pip=7.1.0=py34_1
- py=1.4.30=py34_0
- pytest=2.7.2=py34_0
- python=3.4.3=0
- readline=6.2=2
- requests=2.7.0=py34_0
- setuptools=18.1=py34_0
- six=1.9.0=py34_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- wheel=0.24.0=py34_0
- xz=5.0.5=0
- zlib=1.2.8=0
- pip:
  - accloudtant (/Users/ifosch/src/github.com/ifosch/accloudtant)==0.0.1.dev1

