name: accloudtant
channels:
    - natx
dependencies:
    - click=4.1=py34_0
    - flake8=2.3.0=py34_0
    - mccabe=0.3=py34_1
    - openssl=1.0.1k=1
    - pep8=1.6.2=py34_0
    - pip=7.1.2=py34_0
    - py=1.4.30=py34_0
    - pyflakes=0.9.2=py34_0
    - pytest=2.7.2=py34_0
    - python=3.4.3=0
    - pyyaml=3.11=py34_1
    - readline=6.2=2
    - requests=2.7.0=py34_0
    - setuptools=18.3.2=py34_0
    - six=1.9.0=py34_0
    - sqlite=3.8.4.1=1
    - tabulate=0.7.5=py34_0
    - tk=8.5.18=0
    - wheel=0.26.0=py34_1
    - xz=5.0.5=0
    - yaml=0.1.6=0
    - zlib=1.2.8=0
